### ISSUE TITLE
Too much slow video speed

### ISSUE THREAD

**Issue by kishan-chauhan** [saimj7/Social-Distancing-Detection-in-Real-Time#2]
Hi,
I have installed & working well but video speed is too much slow. frame are lagging too much

**Comment by saimj7** [comment]
Hi, are you using the GPU?

**Comment by kishan-chauhan** [comment]
Yes, i have installed

**Comment by saimj7** [comment]
You should run this within the terminal where OpenCV is built from scratch, in order to use the GPU. Also, threading helps to further smoothen the video stream.

**Comment by kishan-chauhan** [comment]
Okay, thanks Sai Subhakar
