### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by johnbone25** [saimj7/Social-Distancing-Detection-in-Real-Time#5]
Why do i have this error? How can i do to solve this?

![image](https://user-images.githubusercontent.com/82903709/116003901-849ca000-a600-11eb-9915-eef2c120b043.png)

**Comment by saimj7** [comment]
The FPS counter tries to divide the elapsed total no. of frames with time (from start to end). Were you able to see the output? My best guess is the program didn't run (hence zero division error as elapsed time = 0). Try to comment out the FPS part and re-run.

**Comment by johnbone25** [comment]
No, i cant't see output. But where should it be? I need to know the distance between people
should I comment on line 33 of this image?  
![image](https://user-images.githubusercontent.com/82903709/116133097-9cdaf080-a6ce-11eb-833e-15bb241dcfb0.png)

**Comment by saimj7** [comment]
By output, I meant the video stream. No, try to comment out all the lines related to fps in 'Run.py' and check for errors.

**Comment by johnbone25** [comment]
I try to do it, but now there is this error. How can i do to solve this?
![image](https://user-images.githubusercontent.com/82903709/116251202-be8bb480-a76e-11eb-824c-d0f01f902cab.png)

**Comment by johnbone25** [comment]
Ok, now work well! But these instructions are important? What do they are?
However it is possible to print the distance between persons? In what variable it is?
Thanks so much

**Comment by saimj7** [comment]
FPS/Frames per second implies the total no. of frames being processed w.r.t time. It is useful in measuring your machine's computational capacity. For instance, using a GPU can make your system faster == high fps. Coming to distance, please refer to #4.

**Comment by johnbone25** [comment]
ok, thanks. But is it possible to print the distance between persons?

**Comment by johnbone25** [comment]
So,  what variable are the pair-wise pixel differences between people in? Can i print?

**Comment by saimj7** [comment]
Sure, they are stored in a matrix D (line 89) after computing the Euclidean distances between all pairs of the centroids (people). You can just 'print(D)' the matrix.

**Comment by johnbone25** [comment]
Thanks
