### ISSUE TITLE
 [Errno 2] No such file or directory: 'yolo\\coco.names'

### ISSUE THREAD

**Issue by trapti099** [saimj7/Social-Distancing-Detection-in-Real-Time#8]
File "c:/Users/trapt/Downloads/Social-Distancing-Detection-in-Real-Time-main/Social-Distancing-Detection-in-Real-Time-main/Run.py", line 27, in <module>
    LABELS = open(labelsPath).read().strip().split("\n")
FileNotFoundError: [Errno 2] No such file or directory: 'yolo\\coco.names'

**Comment by saimj7** [comment]
Weird, everything works just fine.. you sure cloned the repo and have all the files existing in one place/directory? Do you actually see 'coco.names' in your yolo folder?

**Comment by trapti099** [comment]
Yes I have all the files at correct place/folder.
Can't figure out the problem.

**Comment by saimj7** [comment]
What terminal are you using? e.g., cmd? or from where/how are you running? You cannot just open and run it, you need to actually open the folder path in your editor or terminal, and then run it.
