### ISSUE TITLE
(-215:Assertion failed) !_filename.empty()

### ISSUE THREAD

**Issue by trapti099** [saimj7/Social-Distancing-Detection-in-Real-Time#9]
[INFO] Looking for GPU
[INFO] Starting the live stream..
[ERROR:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap.cpp (116) cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\videoio\src\cap_images.cpp:293: error: (-215:Assertion failed) !_filename.empty() in function 'cv::CvCapture_Images::open'

**Comment by saimj7** [comment]
Need more details, have you built OpenCV with CUDA support (for an NVIDIA GPU)?

**Comment by trapti099** [comment]
No, I am using AMD GPU

**Comment by saimj7** [comment]
I don't think you can use cuda with an amd gpu out of the box, not sure what could be an alternative. Have you managed to run this on cpu?
